pipeline:
  name: testing
  identifier: testing
  projectIdentifier: vasu_test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: stepgroup
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: new_k8_connector
            failureStrategies: <+input>
          execution:
            steps:
              - step:
                  type: K8sRollingDeploy
                  name: K8sRollingDeploy_1
                  identifier: K8sRollingDeploy_1
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  timeout: 10m
                  failureStrategies:
                    - onFailure:
                        errors:
                          - UserMarkedFailure
                        action:
                          type: Abort
            rollbackSteps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: exit 12
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: PipelineRollback
